imports:
  - { resource: Backend/DashboardWidgets.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DanielSiepmann\Tracking\:
    resource: '../Classes/*'
    exclude: '../Classes/Dashboard/*'

  dbconnection.tx_tracking_pageview:
    class: 'TYPO3\CMS\Core\Database\Connection'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getConnectionForTable'
    arguments:
      - 'tx_tracking_pageview'

  querybuilder.tx_tracking_pageview:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getQueryBuilderForTable'
    arguments:
      - 'tx_tracking_pageview'

  dbconnection.tx_tracking_recordview:
    class: 'TYPO3\CMS\Core\Database\Connection'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getConnectionForTable'
    arguments:
      - 'tx_tracking_recordview'

  querybuilder.tx_tracking_recordview:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getQueryBuilderForTable'
    arguments:
      - 'tx_tracking_recordview'

  dbconnection.tx_tracking_tag:
    class: 'TYPO3\CMS\Core\Database\Connection'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getConnectionForTable'
    arguments:
      - 'tx_tracking_tag'

  DanielSiepmann\Tracking\Domain\Repository\Pageview:
    public: true
    arguments:
      - '@dbconnection.tx_tracking_pageview'

  DanielSiepmann\Tracking\Domain\Repository\Recordview:
    public: true
    arguments:
      - '@dbconnection.tx_tracking_recordview'

  DanielSiepmann\Tracking\Domain\Repository\Tag:
    public: true
    arguments:
      - '@dbconnection.tx_tracking_tag'

  DanielSiepmann\Tracking\Middleware\Pageview:
    public: true
    arguments:
      $rule: >
          not (context.getAspect("backend.user").isLoggedIn())
          and not (context.getAspect("frontend.preview").isPreview())

  DanielSiepmann\Tracking\Middleware\Recordview:
    public: true
    arguments:
      $rules: []

  DanielSiepmann\Tracking\Command\UpdateDataCommand:
    tags:
      - name: 'console.command'
        command: 'tracking:updatedata'
        description: 'Updates existing data.'
