name: CI
on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.json') }}

      - uses: php-actions/composer@master

      - name: Upload build for test runner
        uses: actions/upload-artifact@v1
        with:
          name: build-artifact
          path: ./

  cgl:
    runs-on: [ubuntu-latest]
    needs: [build]

    steps:
      - uses: actions/download-artifact@v1
        with:
          name: build-artifact
          path: ./

      - name: Test CGL
        run: ./vendor/bin/phpcs

  test:
    runs-on: [ubuntu-latest]
    needs: [build]

    steps:
      - uses: actions/download-artifact@v1
        with:
          name: build-artifact
          path: ./

      - name: Execute PHPUnit Tests
        run: ./vendor/bin/phpunit
